/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Certificate = {
  _id: string;
  _type: "certificate";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  issuer: string;
  date: string;
  credId?: string;
  order?: number;
};

export type SkillRow = {
  _id: string;
  _type: "skillRow";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label: string;
  items?: Array<string>;
  order?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  role: string;
  description: string;
  tags?: Array<string>;
  href?: string;
  order?: number;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company: string;
  role: string;
  period: string;
  description: string;
  tags?: Array<string>;
  order?: number;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroRole?: string;
  heroLocation?: string;
  heroFirstName?: string;
  heroLastName?: string;
  heroMantra?: string;
  navLinks?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
  overviewHeadline?: string;
  overviewBody1?: string;
  overviewBody2?: string;
  overviewItems?: Array<string>;
  socialLinks?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
  band1?: Array<string>;
  band2?: Array<string>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Certificate
  | SkillRow
  | Project
  | Experience
  | Settings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/sanity/queries/index.ts
// Variable: SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{    heroRole,    heroLocation,    heroFirstName,    heroLastName,    heroMantra,    navLinks[] { label, href },    overviewHeadline,    overviewBody1,    overviewBody2,    overviewItems[],    socialLinks[] { label, href },    band1[],    band2[]  }
export type SETTINGS_QUERY_RESULT =
  | {
      heroRole: null;
      heroLocation: null;
      heroFirstName: null;
      heroLastName: null;
      heroMantra: null;
      navLinks: null;
      overviewHeadline: null;
      overviewBody1: null;
      overviewBody2: null;
      overviewItems: null;
      socialLinks: null;
      band1: null;
      band2: null;
    }
  | {
      heroRole: string | null;
      heroLocation: string | null;
      heroFirstName: string | null;
      heroLastName: string | null;
      heroMantra: string | null;
      navLinks: Array<{
        label: string | null;
        href: string | null;
      }> | null;
      overviewHeadline: string | null;
      overviewBody1: string | null;
      overviewBody2: string | null;
      overviewItems: Array<string> | null;
      socialLinks: Array<{
        label: string | null;
        href: string | null;
      }> | null;
      band1: Array<string> | null;
      band2: Array<string> | null;
    }
  | null;

// Source: src/sanity/queries/index.ts
// Variable: EXPERIENCES_QUERY
// Query: *[_type == "experience"] | order(order asc){    company,    role,    period,    description,    tags[]  }
export type EXPERIENCES_QUERY_RESULT = Array<{
  company: string;
  role: string;
  period: string;
  description: string;
  tags: Array<string> | null;
}>;

// Source: src/sanity/queries/index.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(order asc){    title,    role,    description,    tags[],    href  }
export type PROJECTS_QUERY_RESULT = Array<{
  title: string;
  role: string;
  description: string;
  tags: Array<string> | null;
  href: string | null;
}>;

// Source: src/sanity/queries/index.ts
// Variable: SKILL_ROWS_QUERY
// Query: *[_type == "skillRow"] | order(order asc){    label,    items[]  }
export type SKILL_ROWS_QUERY_RESULT = Array<{
  label: string;
  items: Array<string> | null;
}>;

// Source: src/sanity/queries/index.ts
// Variable: CERTIFICATES_QUERY
// Query: *[_type == "certificate"] | order(order asc){    name,    issuer,    date,    credId  }
export type CERTIFICATES_QUERY_RESULT = Array<{
  name: string;
  issuer: string;
  date: string;
  credId: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "siteSettings"][0]{\n    heroRole,\n    heroLocation,\n    heroFirstName,\n    heroLastName,\n    heroMantra,\n    navLinks[] { label, href },\n    overviewHeadline,\n    overviewBody1,\n    overviewBody2,\n    overviewItems[],\n    socialLinks[] { label, href },\n    band1[],\n    band2[]\n  }\n': SETTINGS_QUERY_RESULT;
    '\n  *[_type == "experience"] | order(order asc){\n    company,\n    role,\n    period,\n    description,\n    tags[]\n  }\n': EXPERIENCES_QUERY_RESULT;
    '\n  *[_type == "project"] | order(order asc){\n    title,\n    role,\n    description,\n    tags[],\n    href\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "skillRow"] | order(order asc){\n    label,\n    items[]\n  }\n': SKILL_ROWS_QUERY_RESULT;
    '\n  *[_type == "certificate"] | order(order asc){\n    name,\n    issuer,\n    date,\n    credId\n  }\n': CERTIFICATES_QUERY_RESULT;
  }
}
